In [6]:
import numpy as np
import random
import matplotlib.pyplot as plt
import pandas as pd
import math
import sklearn
import matplotlib
import sys
import scipy
%matplotlib inline
plt.style.use('seaborn')

In [ ]:

class decision_tree_regressor:
    
    def __init__(self, max_depth = None, criteria ='std'):
        """
        KWargs:
        max_depth number of splits
        criteria: metric to measure the split strength
        std = to reduce the standewd deviation 
        """
        self.tree = self.tree_split()
        self.data_cols = None
        self.max_depth = max_depth
        self.current_depth = 0
        self.criteria = criteria
        
    # Sub class is used to handle the recursive nods
    
    class tree_split:
        """
        each node contains the value and column for the current split
        """
        def __init__(self,col=-1,value=None,results=None,label=None,tb=None,fb=None)
        self.col = col # column index for the current split
        self.value = value #
        self.tb = tb # true decision node
        self.fb = fb # false decision node
        self.results = results #
        
    def pandas_to_numpy(self, x):
        
        if type(x) == type(pd.DataFrame()) or typr(pd.series()):
            return x.as_matrix()
        if type(x) == type(np.array([1,1])):
            return x
        
    def handle_1d_data(self, x):
        
        if x.ndim == 1:
            x = x.reshape(-1, 1)
        return x
    
    def convert_to_array(self, x):
        
        x = self.pandas_to_numpy(x)
        x = self.handle_1d_data(x)
        return x
    
    def split_data(self, X, y, colnum, value):
        """
        out: returns two sets of data. set 1 if condition is passed
        else set 2
        input: The dataset, the column to split on, the value on which to split
        """
        split = None
        if isinstance(value, int) or isinstance(value, float):
            split = lambda x: x[colnum] >= value  # numerical
        else:
            split = lambda x: x[colnum] == value  # catagorical
        
        true_index = [i for i,v in enumerate(split) if v == True]
        flase_index = [i for i,v in enumerate(split) if v == False]
        t_s_x = X[true_index]
        t_s_y = y[true_index]
        f_s_x = X[flase_index]
        f_s_y = y[flase_index]
        return t_s_x, t_s_y, f_s_x, f_s_y 
        
        
        
    def split_criteria(self, y): 
        """
        returns the criteria we are trying to min
        input: targets in the split
        out: Criteria
        """
        if self.criteria == 'mae':
            mu = np.mean(y)
            return np.mean(np.abs(y - mu))
        if self.criteria == 'std':
            return np.std(y)
        
    def get_mean_target_value(self, data):
        """
        out: a dic of target variables in the data
        """
        return np.mean(data)
    
    def _fit(self, X, y, depth = 0):
        """
        Checks every possible branch for the best current decision
        if no information gain then sets that node to leaf node
        if max depth is met, all further nodes becomes leaves as well
        """
        X = self.convert_to_array(X)
        y = self.convert_to_array(y)
        
        if len(X) == 0: return tree_split()
        current_score = self.split_criteria(y)
        
        best_gain = 0.0
        best_criteria = None
        best_set = None
        
        self.data_cols = X.shape[1]
        
        """
        we go through each column and try every possible split
        then measure information gain to select the best split
        after the split the split data set is sent to the next phase of splitting
        """
        
        for col in range(self.data_cols):
            column_values = set(X[col])   # c
            for value in colum_values:
                set1, set1_y, set2, set2_y = self.split_data(X, y, col, value)
                p = float(len(set1))/ len(y)
                gain = current_score - p*self.split_criteria(set1) - (1-p)*self.split_criteria(set2)
                if gain > best_gain and len(set1_y) and len(set2_y):
                    best_gain = gain
                    best_criteria = (col, val)
                    best_sets = (np.array(set1), np.array(set1_y), np.array(set2), np.array(set2_y))
        
        # checking for end point.
        if(self.max_depth and depth < self.max_depth):   #c
            if best_gain > 0:
                self.current_depth += 1
                true_branch = self._fit(best_sets[0], best_sets[1], depth = depth+1)
                false_branch = self._fit(best_sets[2], best_sets[3], depth = depth+1)
                return self.tree_split(col=best_criteria[0], value=best_criteria[1],
                        tb=true_branch, fb=false_branch)
            else:
                return self.tree_split(result = self.get_mean_target_value(y))
        else:
            return self.tree_split(result = self.get_mean_target_value(y))
        
        
        
    def fit(self, X, y):
        '''
        fit is defined seperately because _fit takes care of recursion. 
        '''
        return _fit(self, X, y, depth = 0)
    
    
    
    
    
    
            
        
            

In [41]:
a = np.array(np.arange(9))
b = set(a)
for i in b:
    print(i)

0
1
2
3
4
5
6
7
8


In [22]:
a[1]

array([3, 4, 5])

In [26]:
df = pd.DataFrame({'one': pd.Series((1,2,3,4), index =[1,2,3,4]), 'two': pd.Series((5,6,7,8),index =[1,2,3,4])})
df

one  two
1    1    5
2    2    6
3    3    7
4    4    8

In [29]:
dfm = df.as_matrix()
dfm

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]], dtype=int64)

In [30]:
dfm[1]

array([2, 6], dtype=int64)

In [4]:
ml = [[1,2],[3,4]]


TypeError: unhashable type: 'list'

In [5]:
split = [True, True, True, True, False, False ]
true_index =[i for i,v in enumerate(split) if v == True]
true_index

[0, 1, 2, 3]

In [13]:
x = np.array([1,2,3,4,5,6])
split = np.array(x >= 4)
split1 = [i for i,row in np.ndenumerate(x) if split(row)]
split1

TypeError: 'numpy.ndarray' object is not callable

In [15]:
a = [1,2,3]
b = [1,2]
set(b).issubset(a)

True

In [18]:
a = [True, False]
print(not(False in a))

False
